### ISSUE TITLE
A new version with add and sub to npm?

### ISSUE THREAD

**Issue by copkiller** [errcw/gaussian#10]
I noticed that add and sub are missing from 1.0.0. Any chance of getting a new version with those functions?

**Comment by errcw** [comment]
Yes, thanks for pointing out the issue, I should update the package. I hope to get to it in a few days when I have a few spare minutes.

**Comment by copkiller** [comment]
Thx!



—

**Comment by errcw** [comment]
Done! I've published version 1.1.0.
