### ISSUE TITLE
npm version of package does not include custom random function code

### ISSUE THREAD

**Issue by timmb** [errcw/gaussian#18]
Sorry if I'm missing something obvious here. But when pulling the package from npm I find there is no custom rand function for Gaussian.random.

See [here](https://npm.runkit.com/gaussian/lib/gaussian.js)

Both npm and Github report version 1.2.0.

But on Github in `gaussian.js` we have:

```
  Gaussian.prototype.random = function(num, randFn = null){
    let mean = this.mean;
    let std = this.standardDeviation;
    return Array(num).fill(0).map(() => {
      return generateGaussian(mean,std, randFn)
    })
  };
```

And on npm we have

```
  // Generate [num] random samples
  Gaussian.prototype.random = function(num){
    let mean = this.mean;
    let std = this.standardDeviation;
    return Array(num).fill(0).map(() => {
      return generateGaussian(mean,std)
    })
  };
```

**Comment by errcw** [comment]
I've (finally) pushed version 1.3 to npm that includes this update. (Apologies for the incredible delay here; it's been a busy year and I've had all my open source commitments on pause.)
