### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by f-wrobel** [errcw/gaussian#19]
Hi, I would like to ask: is this library still maintained?

**Comment by errcw** [comment]
Perhaps "mostly" is the most honest answer. I just pushed version 1.3 to npm that includes the most recent changes to the library. But beyond those changes I think this library is mostly "done", i.e., I don't expect an ongoing stream of changes.

**Comment by f-wrobel** [comment]
Okay, thanks for clarification :)
