### ISSUE TITLE
[release-request] 1.2.0 doesn't expose the package license correctly

### ISSUE THREAD

**Issue by ghost** [errcw/gaussian#20]
Our automatic license checker script forbids this library because the latest 1.2.0 version doesn't expose the license correctly.

This was already fixed in master. **Would it be possible to release a new version with the fix?** :pray: 

![image](https://user-images.githubusercontent.com/57348810/213102948-995a6085-5514-4630-b576-77a3912afbcc.png)

**Comment by errcw** [comment]
Thanks for the report! I've pushed version 1.3 to npm that includes this license fix and verified that https://www.npmjs.com/package/gaussian now lists the MIT license.
