### ISSUE TITLE
Bug on Percentage pointer function  (ppf)

### ISSUE THREAD

**Issue by suis** [errcw/gaussian#7]
Hi all,
looks like there is a bug on : https://github.com/errcw/gaussian/blob/master/test/gaussian.js

line number : 56 

we don't seems to get a correct result on below calculation

var d = gaussian(0, 1);
test.epsilonEqual(d.ppf(0.5), 0);

expected result wont be  : 0     when the   .ppf(0.5)
mean = 0 
variance = 1

any idea ?

thanks

**Comment by suis** [comment]
I always get the value of : 3.7599186848597124

**Comment by suis** [comment]
sorry guys it was my mistake..the actual value that I was getting : 3.7599186848597124e-8 
which is :  0.000000037599186848597124    

so the there is no bug   at all...
please ignore this issue ..

**Comment by errcw** [comment]
No problem, thanks for following up.
