### ISSUE TITLE
Documentation about sampling

### ISSUE THREAD

**Issue by axelpale** [errcw/gaussian#9]
The following usage example would help the user to (a) understand how 'distribution' object should be used, (b) how to sample the distribution, and (c) what is the typical purpose of ppf method:

    var gaussian = require('gaussian');
    var distribution = gaussian(mean, variance);
    // Take a random sample
    var sample = distribution.ppf(Math.random());

**Comment by errcw** [comment]
Thanks for the suggestion, I've added your proposal!

**Comment by axelpale** [comment]
Great, nice :)
